// <auto-generated />
namespace Iruka.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_priority : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_priority));
        
        string IMigrationMetadata.Id
        {
            get { return "201911020340086_add_priority"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
