// <auto-generated />
namespace Iruka.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_baseentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_baseentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201910310205240_update_baseentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
