// <auto-generated />
namespace Iruka.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_transaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_transaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201911120626457_add_transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
